<a href="https://colab.research.google.com/github/Rohit-VN/PyTorch-Practice/blob/main/00_pytoch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
# Re-import torch to reset the 'torch.manual_seed' function if it was accidentally overwritten.
import torch
print("torch re-imported to ensure 'torch.manual_seed' is callable.")

torch re-imported to ensure 'torch.manual_seed' is callable.


In [ ]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
scalar.item()
scalar.shape


tensor(7)
0


torch.Size([])

In [ ]:
# Vector
vector = torch.tensor([7,7])
print(vector)
vector.ndim , vector.shape


tensor([7, 7])


(1, torch.Size([2]))

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX
MATRIX.ndim , MATRIX.shape

(2, torch.Size([2, 2]))

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [ ]:
# Random TENSOR
random_tensor = torch.rand(size=(3,4))
random_tensor
random_image_tensor = torch.rand(size = (224, 224, 3))
random_image_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
# 0 and 1 Tensor
zeros_tensor = torch.zeros(size = (3,4))
ones_tensor = torch.ones(size = (3,4))
zeros_tensor , ones_tensor

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [ ]:
# Range in Tensors
tensor_1_10 = torch.arange(start = 1,end = 11,step = 1)
tensor_1_10
new_zero_tensor = torch.zeros_like(input = tensor_1_10)
new_one_tensor = torch.ones_like(input = tensor_1_10)
new_zero_tensor, new_one_tensor

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [ ]:
# Data types within Tensors
new_tensor = torch.tensor([1.0,2.0,3.0])
new_tensor.dtype , new_tensor.device , new_tensor.requires_grad
new_2_tensor = torch.tensor([1.0,2.0,3.0],dtype = torch.float16)
new_2_tensor.dtype

random_tensor = torch.rand(size = (3,4))
print(random_tensor)
print(random_tensor.dtype)
print(random_tensor.device)
print(random_tensor.shape)



tensor([[0.2949, 0.3475, 0.4451, 0.5898],
        [0.3977, 0.5633, 0.5323, 0.5500],
        [0.5338, 0.2284, 0.1392, 0.4811]])
torch.float32
cpu
torch.Size([3, 4])


In [ ]:
# Tensor Operations
tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 10
tensor = tensor - 10
tensor + 10
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([10,20,30])
tensor_3 = tensor_1 * tensor_2
tensor_3 , torch.multiply(tensor_1,tensor_2)


(tensor([10, 40, 90]), tensor([10, 40, 90]))

In [ ]:
# Matrix Multiplication
tensor_1 = torch.tensor([[1,2],[3,4]])
tensor_2 = torch.tensor([[5,6],[7,8]])
print(tensor_1.ndim)
print(tensor_2.ndim)
tensor_3 = torch.matmul(tensor_1,tensor_2)
tensor_3

2
2


tensor([[19, 22],
        [43, 50]])

In [ ]:
# Tensor Transpose
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
print(tensor_A.shape)
print(tensor_B.shape)

# torch.matmul(tensor_A, tensor_B) --> (this will error)
# We need to transpose
result_tensor = torch.mm(tensor_A,tensor_B.T)
result_tensor, result_tensor.shape

torch.Size([3, 2])
torch.Size([3, 2])


(tensor([[ 27.,  30.,  33.],
         [ 61.,  68.,  75.],
         [ 95., 106., 117.]]),
 torch.Size([3, 3]))

In [ ]:
torch.manual_seed(7)
tensor_x = torch.rand(size = (3,4))
linear = torch.nn.Linear(in_features = 4 , out_features = 2 , bias = False)
output = linear(tensor_x)
print(tensor_x.shape)
print(output.shape)
print(linear.weight.shape)


torch.Size([3, 4])
torch.Size([3, 2])
torch.Size([2, 4])


In [ ]:
new_tensor = torch.arange(start = 0,end = 100,step = 10)
new_tensor
print(new_tensor)
print(new_tensor.max())
print(new_tensor.min())
print(new_tensor.sum())
print(new_tensor.type(torch.float32).mean())
print(new_tensor.argmax())
print(new_tensor.argmin())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(90)
tensor(0)
tensor(450)
tensor(45.)
tensor(9)
tensor(0)


In [ ]:
# Change the datatype
new_tensor = torch.arange(1,100,10)
new_tensor.dtype
new_tensor_float32 = new_tensor.type(torch.float32)
new_tensor_float32.dtype
new_tensor_float16 = new_tensor_float32.type(torch.half)
new_tensor_float16.dtype
new_tensor_int8 = new_tensor_float16.type(torch.int8)
new_tensor_int8.dtype

torch.int8

In [ ]:
# Reshaping, stacking, squeezing and unsqueezing
# Reshaping
tensor = torch.arange(1.,9.)
tensor.shape
tensor_new = tensor.reshape(1,8)
tensor_new.shape
x = tensor_new.view(2,4)
x[0][3] = 100
x,tensor_new

# Stacking
tensor_1 = torch.arange(0,11)
tensor_2 = torch.arange(10,21)
tensor_3 = torch.arange(20,31)
tensor_stack = torch.stack([tensor_1,tensor_2,tensor_3],dim = 1)
tensor_stack

tensor([[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22],
        [ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25],
        [ 6, 16, 26],
        [ 7, 17, 27],
        [ 8, 18, 28],
        [ 9, 19, 29],
        [10, 20, 30]])

In [ ]:
# Squeezing
x.shape
x = x.reshape(1,1,1,1,1,1,4,2,1)
x = x.squeeze()
x = x.unsqueeze(2)
x.shape

torch.Size([4, 2, 1])

In [ ]:
# Permutation
tensor = torch.rand(224,224,3)
tensor = tensor.permute(2,1,0)
tensor.shape

torch.Size([3, 224, 224])

In [ ]:
# Indexing
tensor = torch.arange(1,10).reshape(1,3,3)
print(tensor[0])
print(tensor[0,0])
print(tensor[0,:,0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor([1, 4, 7])


In [ ]:
# PyTorch tensors & NumPy
import numpy as np
np_array = np.array([1.0,2.0,3.0])
tensor = torch.from_numpy(np_array)
np_array[1] = 30
tensor = tensor.type(torch.float32)
tensor,tensor.dtype

new_tensor = torch.arange(1,10)
new_np_array = new_tensor.numpy()
new_tensor[0] = 100
new_np_array

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
# Device
torch.cuda.is_available()
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
device
tensor = torch.rand(3)
tensor.to(device)
torch.cuda.device_count()

1

In [ ]:
tensor_1 = torch.rand(3)
print(tensor_1.device)
if torch.cuda.is_available():
  device = torch.device('cuda')
  tensor_1 = tensor_1.to(device)
  print(tensor_1.device)

cpu
cuda:0


In [ ]:
# NumPy works only on CPU
tensor = torch.rand(7)
tensor = tensor.to(torch.device('cuda'))
tensor.device
# tensor_numpy = tensor.numpy() --> Error
tensor_numpy = tensor.cpu().numpy()
tensor_numpy

array([0.77662176, 0.4985804 , 0.7709283 , 0.9641723 , 0.09557384,
       0.85235965, 0.560491  ], dtype=float32)

In [ ]:
# Exercises

#2. Create a random tensor with shape (7, 7).
tensor_1 = torch.rand(7,7)
tensor_2 = torch.rand(1,7)
print(tensor_1.shape,tensor_2.shape)

#3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
tensor_3 = torch.mm(tensor_1,tensor_2.T)
print(tensor_3.shape)

#4. Set the random seed to 0 and do exercises 2 & 3 over again.'
torch.manual_seed(0)
tensor_1 = torch.rand(7,7)
tensor_2 = torch.rand(1,7)
print(tensor_1.shape,tensor_2.shape)
tensor_3 = torch.mm(tensor_1,tensor_2.T)
print(tensor_3.shape)

#5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
#If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

#6. Create two random tensors of shape (2, 3) and send them both to the GPU. Set torch.manual_seed(1234) when creating the tensors
torch.manual_seed(1234)
tensor_1 = torch.rand(2,3)
tensor_2 = torch.rand(2,3)
if torch.cuda.is_available():
  device = torch.device('cuda')
  tensor_1 = tensor_1.to(device)
  tensor_2 = tensor_2.to(device)
  print(tensor_1.device)
  print(tensor_2.device)

#7. Perform a matrix multiplication on the tensors you created in 6
tensor_3 = torch.mm(tensor_1,tensor_2.T)
print(tensor_3)

#8. Find the maximum and minimum values of the output of 7.
print(tensor_3.max())
print(tensor_3.min())

#9. Find the maximum and minimum index values of the output of 7.
print(tensor_3.argmax())
print(tensor_3.argmin())

#10. Make a random tensor with shape (1, 1, 1, 10) and then
#    create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
#    Set the seed to 7 when you create it and print out the first tensor and
#    it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
tensor = torch.rand(1,1,1,10)
print(tensor,tensor.shape)
new_tensor = tensor.squeeze()
print(new_tensor,new_tensor.shape)






torch.Size([7, 7]) torch.Size([1, 7])
torch.Size([7, 1])
torch.Size([7, 7]) torch.Size([1, 7])
torch.Size([7, 1])
cuda:0
cuda:0
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')
tensor(3, device='cuda:0')
tensor(0, device='cuda:0')
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
